### ISSUE TITLE
use the Button class instead of getraw button methods

### ISSUE THREAD

**Issue by preuss812** [preuss812/FRC_2015#2]

**Comment by rmunro21** [comment]
We wrote some code tonight to link a JoystickButton to a Command class.  This functionality is still incomplete as it does not fire the Command::Execute() function when the prescribed button is pressed.  The classes and code need to be researched further to find if there is other configuration required.

**Comment by dkoneill** [comment]
This looks somewhat useful
http://wpilib.screenstepslive.com/s/3120/m/7952/l/97457-running-commands-on-joystick-input

**Comment by rmunro21** [comment]
I did a little more research on this and it appears that the Command infrastructure requires some other components.  You can see the other components required by creating a command-based project in Eclipse.  This is done by selecting File->New->Other...  In the Wizard dialog select WPILib Robot C++/Robot C++ Project and Next.  Then select the Command Based Robot item in the Project Type area.  After naming the project and selecting Finish the skeleton project will have the required code and example implementation of a Command class.

It appears that the Scheduler::Run() function must be called for button processing to occur.

**Comment by rmunro21** [comment]
Dan, 
That is the webpage that we saw when gathering information to implement code earlier today.  It doesn't mention the supporting code that's required though.

**Comment by diespinoza** [comment]
Today we made the new object based project. We are not sure if it was running correctly. We tried to make a new command but we had some trouble. It said that the declaration was not found.

**Comment by rmunro21** [comment]
By adding the instruction Scheduler::GetInstance->Run() to the TeleopPeriodic() function the Command class that was being instantiated was called as expected in response to presses to button 1 on the left joystick.  Two Command classes were then created and linked to buttons 1 and 2: ExtendRightWiper and RetractRightWiper.  This approach is well suited for button press operations and can be expanded where appropriate.
